### ISSUE TITLE
Species not found in EOL, but it is

### ISSUE THREAD

**Issue by ljvillanueva** [MapofLife/vernacular-names#76]
When trying *Pieris sisymbrii*, the app indicates that "Scientific name not found". But it is in EOL (http://eol.org/pages/28734266/overview). 

Perhaps this has to do with the EOL API returning something that is not recognized? A search in EOL for that species returned 8 results.

**Comment by gaurav** [comment]
This occurs because the EOL API can't find an exact match for _Pieris sisymbrii_ (http://eol.org/api/search/1.0.json?q=Pieris%20sisymbrii&exact=1). The other matches show up if we do a non-exact match (http://eol.org/api/search/1.0.json?q=Pieris%20sisymbrii&exact=0).

I'll turn off exact matching in the next release; let me know if that causes more problems than it solves!
